FORMAT: 1A
HOST: https://api.bitsign.io/

# Bitsign BaaS API documentation

![Bitsign](https://bitsign.io/img/logos/logo.png "Bitsign Logo")
Version: 0.1.0

##### What is  Bitsign Baas?

Bitsign's BaaS **(Blockchain as a Service)** is a service which acts as an
abstraction layer and lets you interact with different types of blockchains and
run descentralized apps (DApps) like Smart Contracts.

Bitsign resources can be found here:

https://github.com/cryptol0g1c/bitsign

Anytime you alter the blockchain state thus creating a transaction that information can
be searched using transaction hash, account or smart contract address at:

https://explorer.bitsign.io

In depth information about the service and it's endpoints can be found here:
[http://bitsign.readthedocs.io/en/latest/](http://bitsign.readthedocs.io/en/latest/)

##### Blockchain types

* BSG blockchain

Bitsign chain is an Ethereum opcode compatible chain that runs on several
Parity nodes using **PoA** (Proof of Authority) consensus algorithm.
Chain parameters and initial conditions can be found here:

https://github.com/cryptol0g1c/bitsign/blob/master/genesis.json

New nodes can be addeed using a validator contract, its code can be found here:

https://github.com/cryptol0g1c/bitsign/blob/master/contracts/validator.sol

* Ropsten Blockchain (WIP)

* Ethereum Main Net (WIP)

* RSK (WIP)

* MultiChain (WIP)


### Get Bitsign Status [GET /status]
This endpoint returns Bitsign blockchain status, latestblock, bootnodes, etc.

+ Response 200 (application/json)

        {
          "success": true,
          "data": {
            "status": "Running, healthy",
            "lastblock": 20201,
            "hash": "0x2c1b018d0cb86087f7e226459e998e6b7515bc6bf529833c90f8e3883d290c49",
            "timestamp": 1515282880,
            "explorer": "https://explorer.bitsign.io/block/20201",
            "bootnodes": [
              "enode://a891225909f70a4ee3f40c1dac05da763fe0354d5f259922abf841db51706283d2957c09fc7266e5f4633583a34dbef3f38a769eb35551788740a06e387dfa2a@159.203.176.160:30303",
              "enode://b21d8b85165319a86c822dadcd51fbaf1aca3fe7854df8644c03ac304e34205d31d44d0eac7dd6366a8f8a621eeb2198d9644090d59771148fb3ac92630d2dd6@198.211.100.127:30303"
            ]
          },
          "error": null
        }

## User Endpoints [/api/v2/user]

### User Info [GET /api/v2/user?email={email}&password={password}]
This endpoint retrieves token and Ethereum keys needed to interact with the rest of the endpoints.
**Email** and **password** parameters must be provided.

+ Parameters
    + email: alice@crypto.com (string) - Unique email address.
    + password: some_crafty_password (string) - User password

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "username": "alice",
                "email": "alice@crypto.com",
                "ethereumAddress": "0xA2..99",
                "token": "ey..yk"
            },
            "error": null
        }

### New User [POST]
Create new user trough our API to get token access and pre-configured Ethereum keys.
With the token you can query all other endpoints and interact with all blockchains and the Smart Contracts.

+ Attributes
    + email: alice@crypto.com (string) - Unique email address.
    + password: some_crafty_password (string) - User password.
    + username: alice (string) - Unique user name.

+ Request (application/json)

        {
            "email": "",
            "password": "",
            "username": ""
        }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "_id": "",
                "username": "",
                "email": "",
                "etherAddress": "",
                "etherPrivKey": "",
                "token": ""
            },
            "error": null
        }

### Change Password [PUT]
This endpoint allow the user to changes their password. You must send the old password and the new one that must respect our security policies.

+ Attributes
    + email: alice@crypto.com (string) - Unique email address.
    + password: some_crafty_password (string) - User password.
    + newPassword: new_crafty_password (string) - User new password.

+ Request (application/json)

        {
            "email": "alice@crypto.com",
            "password": "crafty_password!",
            "newPassword": "new_crafty_password"
        }

+ Response 200 (application/json)

        {
          "success": true,
          "data": {
            "_id": "5a..1a",
            "username": "alice",
            "email": "alice@crypto.com",
            "token": "ey..gk"
          },
          "error": null
        }

## Transaction Endpoints [/eth/notarizetx]
### Notarization TX [POST]
This endpoints uses data field input to create a **notary transaction** and include it in a new block.
Transactions from this endpoints will be executed **from Bitsign's main node** to facilitate its creation.
If you want to create your own transaction and send it from your account please use **sendRawTX endpoint instead**.

+ Attributes
    + token: ey..yk (string) - User token.
    + data: 0x..3F (string) - Data to notarize.
    + address: 0x..m3 (string) - User ethereum address.
    + password: new_crafty_password (string) - User password.

+ Request (application/json)

        {
            "token": "<your_token>",
            "data": "<some_hexadecimal_data>",
            "address": "<your_ethereum_address>",
            "password": "<your_password>"
        }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "blockHash": "0x96..3b",
                "blockNumber": 1958,
                "gasUsed": 21136,
                "transactionHash": "0x2d..b7",
                "explorerUrl": "https://explorer.bitsign.io/tx/0x2d49344a2d59d713a2195acd934060d945bb4fc4c0e792d46d1d5e33b67aaeb7"
            },
            "error": null
        }

### Get transactions by user [GET /api/v2/transactions?token={token}&hash={hash}]
This endpoint returns the transactions executed by the user. JWT token is a required parameter, but the tx hash is an optional
parameter.

+ Parameters
    + token: <user_token> - User token.
    + hash: <hash> (optional) - Transaction hash.

+ Response 200 (application/json)

    {
        "success": true,
        "data": [
            {
                "_id": "5a5ccafb6e04ee60282f3c0b",
                "__v": 0,
                "transaction": {
                    "blockNumber": 26198,
                    "hash": "0x295a9ebc3becf2bd508e8fbe16e7d61456aaf0f333faeafbfdc137c44a1fa78b"
                },
                "created": {
                    "by": "5a36ebc6e36eaa130e301e51",
                    "date": "2018-01-15T15:38:35.580Z"
                }
            }
        ],
        "error": null
    }

## Raw Transactions Endpoints [/eth/signedRawTx]

### SendRawTransaction [POST]
If you don't trust or don't want to use the **keypair provided by Bitsign**, you can always call this endpoint that will publish your **offline
signed** raw [transaction](https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction). Bitsign node will only handle gas cost and transaction publication,
but you have to **craft the entire transaction** on your end.
We will be releasing Bitsign tx library to facilitate this process soon.

+ Attributes
    + token: ey..yk (string) - User token.
    + env: production (string) - Environment to deploy the smart contract.
    + tx: 0x..m3 (string) - Signed data.

+ Request (application/json)

        {
            "token": "",
            "env": "",
            "tx": ""
        }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {},
            "error": null
        }

## Smart Contract Endpoints [/eth/contract]
### Deploy new Smart Contract [PUT]
This endpoint allow the user to deploy a new smart contract. The available smart contracts are:

##### Notarize
This smart contract allow the user to notarize documents.
###### Constructor
In order to initialize Notarize contract the user must send an address, that will be set as the owner of the contract. The owner will be the only one that is able to notarize.
###### Methods
* notarize: This method receive as a parameter a bytes32 that will be the evidence to be notarized. The owner of the contract will be the only one that is capable of execute this method. If the sender is not the owner, the tx will be reverted. After the evidence is notarized the Notary event will be raised with two parameters: the evidence and the address.

##### Escrow
This smart contract allows the user to deposit funds in the smart contract and define a buyer and a seller. Each actor can release the funds to the other part based on pre established conditions. Also there is BSG arbiter which act as an impartial third party that can release the payment to one party in case the other part breaks the initial conditions.
###### Constructor
In order to initialize Escrow contract the user must send _seller (address), _buyer (address) and _endTime (uint). The sender of the transaction will be the arbiter of the contract. The arbiter act as an impartial third party. Also the value should be passed in order to set funds on the contract.
###### Methods
* pay: This method can be executed by the buyer or the arbiter. This method will transfer the balance of the contract to the seller address. After that, it will raise the Payout event with two parameters: balance and seller address.
* refund: This method can be executed by the seller or the arbiter. This method will transfer the balance of the contract to the buyer address. After that, it will raise the Refund event with two parameters: balance and buyer address.
* getBalance: This method will return the balance of the contract. It can be executed by any member of the contract.
* kill: This method can be executed by the arbiter only. It will destruct the contract and send the balance of the contract to its address.

#####  NotarizeTX
###### Constructor
In order to initialize NotarizeTx contract the user must send the following values:
buyer (address),
seller (address),
id  (bytes32),
date (string),
value (uint),
hash (bytes32),
status (string),
shipping (string)
###### Methods
* updateStatus: This method can be executed by the buyer or the BSG node. Also it checks that the id passed is the same as one that user sent when deployed. The parameters of this method are status (string), hash (bytes32) and id (bytes32). The main purpose of this method is to update the tx status. After the method notarize the new tx, it raise the NotaryEvt event with the parameters: hash (bytes32) and id (bytes32).
* updateShipping: This method can be executed by the buyer or the BSG node. Also it checks that the id passed is the same as one that user sent when deployed. The parameters of this method are status (string), hash (bytes32) and id (bytes32). The main purpose of this method is to update the tx shipping. After the method notarize the new tx, it raise the NotaryEvt event with the parameters: hash (bytes32) and id (bytes32).

+ Attributes
    + token: ey..yk (string) - User token.
    + env: production (string) - Environment to deploy the smart contract.
    + args
        + _buyer: 0x..yk (string) - Buyer address.
        + _seller: 0x..6f (string) - Seller address.
        + _endTime: 314159 (number) - Escrow automatic endtime.
    + type: Escrow (string) - Contract type to deploy.
    + value: 0 (string) - Value in ethers to send to the smart contract.
    + password: some_crafty_password (string) - User Password.

+ Request (application/json)

        {
            "token": "",
            "env": "production",
            "args": {
                "_buyer": "",
                "_seller": "",
                "_endTime": 314159
            },
            "type": "Escrow",
            "value": "0",
            "password": "<your_password>"
        }

+ Response 200 (application/json)

        {
          "success": true,
          "data": {
            "__v": 0,
            "encodedAbi": "00..84",
            "address": "0x9B..D3",
            "bytecode": "0x60..029",
            "gas": 166571,
            "type": "Notarize",
            "_id": "5a..31",
            "events": [],
            "abi": [
              {
                "signature": "0xcbef362f",
                "type": "function",
                "stateMutability": "nonpayable",
                "payable": false,
                "outputs": [],
                "name": "notarize",
                "inputs": [
                  {
                    "type": "bytes32",
                    "name": "_sghash"
                  }
                ],
                "constant": false
              },
              {
                "signature": "constructor",
                "type": "constructor",
                "stateMutability": "nonpayable",
                "payable": false,
                "inputs": [
                  {
                    "type": "address",
                    "name": "_user"
                  }
                ]
              },
              {
                "signature": "0x8d..f6",
                "type": "event",
                "name": "Notary",
                "inputs": [
                  {
                    "type": "bytes32",
                    "name": "_sghash",
                    "indexed": false
                  },
                  {
                    "type": "address",
                    "name": "_address",
                    "indexed": false
                  }
                ],
                "anonymous": false
              }
            ],
            "owner": {
              "address": "0x06..E4",
              "email": "test@testuser.com"
            },
            "date": {
              "created": "2017-12-09T01:07:30.634Z"
            }
          },
          "error": null
        }

### Contract Usage [GET /eth/contract/doc?token={token}&type={type}]
This endpoint returns smart contract's ABI and functions to use its functionality.

+ Parameters
    + token: <user_token> (string) - User token.
    + type: <contract_name> (string) - Smart Contract type.

+ Response 200 (application/json)

        {
            "success": true,
            "data": [
                {
                    "name": "seller",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "address"
                        }
                    ],
                    "type": "function"
                },
                {
                    "name": "getBalance",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "uint256"
                        }
                    ],
                    "type": "function"
                },
                {
                    "name": "pay",
                    "parameters": [],
                    "return": [],
                    "type": "function"
                },
                {
                    "name": "endTime",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "uint256"
                        }
                    ],
                    "type": "function"
                },
                {
                    "name": "value",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "uint256"
                        }
                    ],
                    "type": "function"
                },
                {
                    "name": "kill",
                    "parameters": [],
                    "return": [],
                    "type": "function"
                },
                {
                    "name": "refund",
                    "parameters": [],
                    "return": [],
                    "type": "function"
                },
                {
                    "name": "buyer",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "address"
                        }
                    ],
                    "type": "function"
                },
                {
                    "name": "arbiter",
                    "parameters": [],
                    "return": [
                        {
                            "name": "",
                            "type": "address"
                        }
                    ],
                    "type": "function"
                },
                {
                    "parameters": [
                        {
                            "name": "_seller",
                            "type": "address"
                        },
                        {
                            "name": "_buyer",
                            "type": "address"
                        },
                        {
                            "name": "_endtime",
                            "type": "uint256"
                        }
                    ],
                    "type": "constructor"
                },
                {
                    "name": "Payout",
                    "parameters": [
                        {
                            "indexed": false,
                            "name": "_value",
                            "type": "uint256"
                        },
                        {
                            "indexed": false,
                            "name": "_to",
                            "type": "address"
                        }
                    ],
                    "type": "event"
                },
                {
                    "name": "Refund",
                    "parameters": [
                        {
                            "indexed": false,
                            "name": "_value",
                            "type": "uint256"
                        },
                        {
                            "indexed": false,
                            "name": "_to",
                            "type": "address"
                        }
                    ],
                    "type": "event"
                }
            ],
            "error": null
        }


### Call Contract Method [POST]

This endpoint allow the user to read the state from the blockchain using contract methods.
This endpoint will not alter blockchain state and therefore wont cost gas.

+ Request (application/json)

        {
            "token": "",
            "address": "",
            "env": "",
            "method": "",
            "args": {}
        }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {},
            "error": null
        }

### Execute Contract Method[PATCH]

This endpoint allow the user to send a transaction to the node and therefore modify the blockchain state.
Altough this method will generally cost gas, there is no limitation about it when using BSG Chain and gast cost will be handled internally.

+ Attributes
    + token: ey..yk (string) - User token.
    + address: production (string) - Contract's address.
    + env: production (string) - Environment.
    + args
      + arg_1
      + arg_2
    + method: pay (string) - Contract's method to execute.
    + password: some_crafty_password (string) - User Password.

+ Request (application/json)

        {
            "token": "",
            "address": "<contract_address>",
            "env": "production",
            "method": "pay",
            "args": {

            },
            "password": "<your_password>"
        }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {},
            "error": null
        }

### Get deployed contracts by user [GET /api/v2/contracts?token={token}]
This endpoint returns the contracts deployed by the user.

+ Parameters
    + token: <user_token> (string) - User token.

+ Response 200 (application/json)

    {
        "success": true,
        "data": [
            {
                "address": "0xb42B83621125b8f523dC3ca197168439e139744D",
                "contractExplorerUrl": "http://explorer.bitsign.io/account/0xb42B83621125b8f523dC3ca197168439e139744D",
                "date": {
                    "created": "2018-03-15T01:13:21.932Z"
                },
                "encodedAbi": "0000000000000000000000000593ce5dc23005d15bdf39be68e84ee83fd6b3be",
                "type": "Notarize",
                "txHash": "0xba1eb2c8ea051b66a24fa300b7c0eec0e7dc4d65552859e0221963658c1d504b",
                "txExplorerUrl": "http://explorer.bitsign.io/tx/0xba1eb2c8ea051b66a24fa300b7c0eec0e7dc4d65552859e0221963658c1d504b"
            }
        ],
        "error": null
    }
